stages:
  - dependences
  - build
  - publish

# --- DESPLIEGUE PROD ---
dependences_prod:
  stage: dependences
  tags: [prod-apps]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  cache:
    key: { files: [package.json] }
    paths: [node_modules]
  script:
    - npm install

build_prod:
  stage: build
  tags: [prod-apps]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  cache:
    key: { files: [package.json] }
    paths: [node_modules]
    policy: pull
  script:
    - rm -rf dist/
    - npx prisma generate
    - npx tsc
    - npx tsc-alias
    - cp -rf public dist/ || true
    - cp -rf mails dist/ || true
    - cp -rf src/fonts dist/fonts || true
    - cp -f .env dist/ || true
  artifacts:
    paths:
      - dist/
      
    expire_in: 30 min

publish_prod:
  variables:
    DEPLOY: "/var/www"
    FOLDER: "api-dms"
  stage: publish
  tags: [prod-apps]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "Limpieza atómica y reinicio Passenger en Backend Prod"
    - rm -rf $DEPLOY/$FOLDER
    - mkdir -p $DEPLOY/$FOLDER/tmp
    - cp -rf $CI_PROJECT_DIR/node_modules $DEPLOY/$FOLDER/
    - cp -rf $CI_PROJECT_DIR/dist/. $DEPLOY/$FOLDER/
    - touch $DEPLOY/$FOLDER/tmp/restart.txt
